name: Incremental PR analysis test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disable shallow clones
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: BEGIN step 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./sonarscanner-msbuild-net46/SonarScanner.MSBuild.exe begin /o:smarichal /k:incre2 /d:sonar.host.url=https://sonarcloud.io /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.verbose=true 
      - name: BUILD step
        run: dotnet build --no-incremental 
      - name: END step
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./sonarscanner-msbuild-net46/SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
